//meta_data.js
export const UPDATE_TITLE = 'UPDATE_TITLE';


//app.js
export const UPDATE_ACTIVE_INFO = 'UPDATE_ACTIVE_INFO';
export const UPDATE_TOAST_SUCCESS = 'UPDATE_TOAST_SUCCESS';
export const UPDATE_TOP_HEADER_INFO = 'UPDATE_TOP_HEADER_INFO';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';
export const UPDATE_BROWSER_HISTORY = 'UPDATE_BROWSER_HISTORY';


//blog.js
export const BLOG_POST_ACTIVITY_START = 'BLOG_POST_ACTIVITY_START';
export const BLOG_POST_ACTIVITY_FAIL = 'BLOG_POST_ACTIVITY_FAIL';
export const GET_BLOG_POST_SUCCESS = 'GET_BLOG_POST_SUCCESS';
export const GET_BLOG_POSTS_SUCCESS = 'GET_BLOG_POSTS_SUCCESS';


//cart.js
export const UPDATE_CART_ITEMS_SUCCESS = 'UPDATE_CART_ITEMS_SUCCESS';